// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2XEfqdBZlEmt1k1EP3PBJpPf8GJlo3FA',
    appId: '1:48430940432:web:3e21596785126e81396595',
    messagingSenderId: '48430940432',
    projectId: 'forest-data-27eb9',
    authDomain: 'forest-data-27eb9.firebaseapp.com',
    storageBucket: 'forest-data-27eb9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJHikjw76eZVwF-AR687KkvWLBYlkmYTU',
    appId: '1:48430940432:android:a43618ab31453474396595',
    messagingSenderId: '48430940432',
    projectId: 'forest-data-27eb9',
    storageBucket: 'forest-data-27eb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByrRJYFmXO5vN2m8gytyQa7Cgy7VbS5eE',
    appId: '1:48430940432:ios:bb6079efcf81df7a396595',
    messagingSenderId: '48430940432',
    projectId: 'forest-data-27eb9',
    storageBucket: 'forest-data-27eb9.firebasestorage.app',
    iosBundleId: 'com.forestcarbon.forestCarbonPlatform',
  );
}
